# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4cfd581803ccd84e4ac5db9beec06bc2d3cccfbbf3129d2dbc8048fa76ae4478cd6300389074bdf58cf48f1dbc6d832c2cff9cf0bf87a3538b7461e0e64f5a

test:
  secret_key_base: c9a33bf7f367e798c5a499769ce98e1e57335051ee4714cc617b62c6a92017d483577fc8c50dee56d1bad17f943614e40dc945e41891ab40cf85e779cdd810ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
